// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_yjFF9hz77GrOaa0UoYy7G9cfvKsrios',
    appId: '1:928129599533:web:6893d20f0c23e3f770d0a4',
    messagingSenderId: '928129599533',
    projectId: 'timesheet-cfa4d',
    authDomain: 'timesheet-cfa4d.firebaseapp.com',
    storageBucket: 'timesheet-cfa4d.firebasestorage.app',
    measurementId: 'G-3TCSWRK6WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJfTbTH002J8j2DULDvLBAK0rEBNFlaA',
    appId: '1:928129599533:android:262265ade1c64eb870d0a4',
    messagingSenderId: '928129599533',
    projectId: 'timesheet-cfa4d',
    storageBucket: 'timesheet-cfa4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgOO25cFNrFjEAgFgBnBQ2_7lIKuUOb1E',
    appId: '1:928129599533:ios:1221a864156ffaad70d0a4',
    messagingSenderId: '928129599533',
    projectId: 'timesheet-cfa4d',
    storageBucket: 'timesheet-cfa4d.firebasestorage.app',
    iosBundleId: 'com.example.timesheetProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgOO25cFNrFjEAgFgBnBQ2_7lIKuUOb1E',
    appId: '1:928129599533:ios:1221a864156ffaad70d0a4',
    messagingSenderId: '928129599533',
    projectId: 'timesheet-cfa4d',
    storageBucket: 'timesheet-cfa4d.firebasestorage.app',
    iosBundleId: 'com.example.timesheetProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_yjFF9hz77GrOaa0UoYy7G9cfvKsrios',
    appId: '1:928129599533:web:56394516723074bc70d0a4',
    messagingSenderId: '928129599533',
    projectId: 'timesheet-cfa4d',
    authDomain: 'timesheet-cfa4d.firebaseapp.com',
    storageBucket: 'timesheet-cfa4d.firebasestorage.app',
    measurementId: 'G-C7EXYZY28G',
  );
}
